import jsPDF from 'jspdf';
import { splitNetWorthItems } from './netWorthOrdering';

interface TaxBreakdownForPdf {
  grossAnnual: number; pensionSacrifice: number; taxableIncome: number; personalAllowance: number;
  incomeTax: number; nationalInsurance: number; totalDeductions: number; netAnnual: number;
  netMonthly: number; netWeekly: number; effectiveRate: number;
  taxBands: { name: string; rate: string; amount: number }[];
  niBands: { name: string; rate: string; amount: number }[];
}

interface SavingsCalcForPdf {
  name: string; income: number; incomeFrequency: string; monthlyIncome: number;
  expenses: { name: string; amount: number; icon?: string }[]; totalExpenses: number;
  monthlySavings: number; annualSavings: number; savingsRate: number;
}

interface NetWorthPdfData {
  assets: { name: string; type: string; value: number }[];
  totalAssets: number; totalDebts: number; netWorth: number;
}

const ink = [17, 24, 39] as const;
const body = [55, 65, 81] as const;
const muted = [107, 114, 128] as const;
const rule = [209, 213, 219] as const;
const fill = [247, 248, 250] as const;
const alternate = [252, 252, 253] as const;
const negative = [185, 28, 28] as const;
const margin = 18;

function fmt(value: number, symbol: string): string {
  return `${symbol}${Math.abs(value).toLocaleString('en-GB', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;
}

function dateLabel(): string {
  return new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
}

/** Neutral paper-report primitives shared by every native PDF. */
function reportPage(doc: jsPDF, title: string, continuation = false): number {
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, pw, ph, 'F');
  const pageTitle = title === 'Net Worth'
    ? (continuation ? 'Net Worth Report — continued' : 'Net Worth')
    : (continuation ? `${title} — continued` : title);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(continuation ? 12 : 18);
  doc.setTextColor(...ink);
  doc.text(pageTitle, margin, 16);
  doc.setDrawColor(...rule);
  doc.line(margin, 21, pw - margin, 21);
  return 29;
}

function footer(doc: jsPDF, text = 'Generated by TakeHomeCalc · Not financial advice'): void {
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(...muted);
  doc.text(text, pw / 2, ph - 8, { align: 'center' });
}

function metadata(doc: jsPDF, value: string, y: number): number {
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(...muted);
  doc.text(`TakeHomeCalc · ${value}`, margin, y);
  return y + 11;
}

function metric(doc: jsPDF, label: string, value: string, y: number, isNegative = false): number {
  doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(...muted);
  doc.text(label.toUpperCase(), margin, y);
  doc.setFontSize(26);
  if (isNegative) doc.setTextColor(...negative); else doc.setTextColor(...ink);
  doc.text(value, margin, y + 10);
  return y + 23;
}

function heading(doc: jsPDF, title: string, y: number): number {
  doc.setFont('helvetica', 'bold'); doc.setFontSize(12); doc.setTextColor(...ink);
  doc.text(title, margin, y);
  return y + 6;
}

function ensure(doc: jsPDF, y: number, needed: number, title: string): number {
  const ph = doc.internal.pageSize.getHeight();
  if (y + needed <= ph - 16) return y;
  doc.addPage();
  return reportPage(doc, title, true);
}

function table(doc: jsPDF, title: string, y: number, headers: string[], rows: string[][], reportTitle: string, negativeColumns: number[] = []): number {
  const pw = doc.internal.pageSize.getWidth();
  const contentW = pw - margin * 2;
  y = ensure(doc, y, Math.min(rows.length, 3) * 7 + 16, reportTitle);
  y = heading(doc, title, y);
  doc.setFillColor(...fill); doc.rect(margin, y, contentW, 7, 'F');
  doc.setFont('helvetica', 'bold'); doc.setFontSize(7); doc.setTextColor(...muted);
  headers.forEach((header, index) => {
    const x = index === headers.length - 1 ? pw - margin - 3 : margin + 3 + (contentW * index) / headers.length;
    doc.text(header, x, y + 4.8, { align: index === headers.length - 1 ? 'right' : 'left' });
  });
  y += 7;
  rows.forEach((row, rowIndex) => {
    y = ensure(doc, y, 8, reportTitle);
    if (rowIndex % 2 === 0) { doc.setFillColor(...alternate); doc.rect(margin, y, contentW, 7, 'F'); }
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8);
    row.forEach((value, index) => {
      const x = index === row.length - 1 ? pw - margin - 3 : margin + 3 + (contentW * index) / row.length;
      if (negativeColumns.includes(index) && value.startsWith('-')) doc.setTextColor(...negative); else doc.setTextColor(...body);
      doc.text(value.slice(0, 46), x, y + 4.8, { align: index === row.length - 1 ? 'right' : 'left' });
    });
    y += 7;
  });
  return y + 9;
}

function takeHomeSummaryRows(result: TaxBreakdownForPdf, symbol: string): string[][] {
  const rows = [
    ['Gross salary', fmt(result.grossAnnual, symbol)],
    ['Personal allowance', fmt(result.personalAllowance, symbol)],
    ['Income tax', `-${fmt(result.incomeTax, symbol)}`],
    ['National Insurance', `-${fmt(result.nationalInsurance, symbol)}`],
    ['Net annual pay', fmt(result.netAnnual, symbol)],
  ];
  if (result.pensionSacrifice > 0) rows.splice(1, 0, ['Salary sacrifice', `-${fmt(result.pensionSacrifice, symbol)}`]);
  return rows;
}

function drawTakeHomeDetails(doc: jsPDF, result: TaxBreakdownForPdf, symbol: string, y: number, title: string): number {
  y = table(doc, 'Pay Summary', y, ['Item', 'Annual amount'], takeHomeSummaryRows(result, symbol), title, [1]);
  y = table(doc, 'Income Tax', y, ['Band', 'Rate', 'Tax'], result.taxBands.map((band) => [band.name, band.rate, fmt(band.amount, symbol)]), title);
  return table(doc, 'National Insurance', y, ['Band', 'Rate', 'NI'], result.niBands.map((band) => [band.name, band.rate, fmt(band.amount, symbol)]), title);
}

export function exportTakeHomePdf(result: TaxBreakdownForPdf, region: string, currencySymbol: string, skipDownload = false): string {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const title = 'Take Home Pay Report';
  let y = reportPage(doc, title);
  y = metadata(doc, `${dateLabel()} · ${region === 'scotland' ? 'Scotland' : 'England / Wales / NI'} · UK Tax Year 2025-26`, y);
  y = metric(doc, 'Monthly take home pay', fmt(result.netMonthly, currencySymbol), y);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(...body);
  doc.text(`${fmt(result.netAnnual, currencySymbol)}/year   ${fmt(result.netWeekly, currencySymbol)}/week   Effective rate ${result.effectiveRate}%`, margin, y);
  drawTakeHomeDetails(doc, result, currencySymbol, y + 13, title);
  footer(doc, 'Generated by TakeHomeCalc · Estimates based on UK HMRC 2025-26 rates · Not financial advice');
  if (!skipDownload) doc.save('take-home-pay-report.pdf');
  return doc.output('datauristring');
}

export function exportHouseholdTakeHomePdf(partner1: TaxBreakdownForPdf, partner2: TaxBreakdownForPdf, name1: string, name2: string, region1: string, region2: string, currencySymbol: string, skipDownload = false): string {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const title = 'Household Take Home Pay Report';
  let y = reportPage(doc, title);
  y = metadata(doc, `${dateLabel()} · UK Tax Year 2025-26`, y);
  const combined = partner1.netMonthly + partner2.netMonthly;
  y = metric(doc, 'Combined monthly take home pay', fmt(combined, currencySymbol), y);
  const combinedGross = partner1.grossAnnual + partner2.grossAnnual;
  const deductions = partner1.incomeTax + partner2.incomeTax + partner1.nationalInsurance + partner2.nationalInsurance;
  const rate = combinedGross ? Math.round((deductions / combinedGross) * 1000) / 10 : 0;
  y = table(doc, 'Household Summary', y + 2, ['Person', 'Region', 'Monthly take home'], [
    [name1, region1 === 'scotland' ? 'Scotland' : 'England / Wales / NI', fmt(partner1.netMonthly, currencySymbol)],
    [name2, region2 === 'scotland' ? 'Scotland' : 'England / Wales / NI', fmt(partner2.netMonthly, currencySymbol)],
    ['Combined', `${rate}% effective rate`, fmt(combined, currencySymbol)],
  ], title);
  y = ensure(doc, y, 20, title);
  y = heading(doc, name1, y); y = drawTakeHomeDetails(doc, partner1, currencySymbol, y + 2, title);
  y = ensure(doc, y, 20, title);
  y = heading(doc, name2, y); drawTakeHomeDetails(doc, partner2, currencySymbol, y + 2, title);
  footer(doc, 'Generated by TakeHomeCalc · Estimates based on UK HMRC 2025-26 rates · Not financial advice');
  if (!skipDownload) doc.save('household-take-home-pay-report.pdf');
  return doc.output('datauristring');
}

export function exportSavingsCalcPdf(data: SavingsCalcForPdf, currencySymbol: string, skipDownload = false): string {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const title = 'Savings Report';
  let y = reportPage(doc, title);
  y = metadata(doc, `${dateLabel()} · ${data.name}`, y);
  y = metric(doc, 'Monthly savings', fmt(data.monthlySavings, currencySymbol), y, data.monthlySavings < 0);
  y = table(doc, 'Income and Savings', y + 2, ['Item', 'Monthly amount'], [
    [`Income (${data.incomeFrequency})`, fmt(data.income, currencySymbol)],
    ['Normalised monthly income', fmt(data.monthlyIncome, currencySymbol)],
    ['Total expenses', `-${fmt(data.totalExpenses, currencySymbol)}`],
    ['Savings rate', `${data.savingsRate}%`],
  ], title, [1]);
  table(doc, 'Expense Breakdown', y, ['Category', 'Monthly amount'], data.expenses.map((expense) => [expense.name, fmt(expense.amount, currencySymbol)]), title, [1]);
  footer(doc);
  if (!skipDownload) doc.save(`savings-report-${data.name.replace(/\s+/g, '-').toLowerCase()}.pdf`);
  return doc.output('datauristring');
}

export function exportNetWorthPdf(data: NetWorthPdfData, currencySymbol: string, skipDownload = false): string {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const title = 'Net Worth';
  let y = reportPage(doc, title);
  y = metadata(doc, dateLabel(), y);
  y = metric(doc, 'Net worth', `${data.netWorth < 0 ? '-' : ''}${fmt(data.netWorth, currencySymbol)}`, y, data.netWorth < 0);
  const pw = doc.internal.pageSize.getWidth();
  doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(...body);
  doc.text(`Assets  ${fmt(data.totalAssets, currencySymbol)}`, margin, y);
  doc.text(`Liabilities  ${fmt(data.totalDebts, currencySymbol)}`, pw - margin, y, { align: 'right' });
  y += 13;
  const ordered = splitNetWorthItems(data.assets);
  const drawItems = (section: 'Assets' | 'Liabilities', items: typeof data.assets, liability: boolean) => {
    y = table(doc, section, y, ['Name', 'Type', 'Value'], items.map((item) => [item.name, item.type, `${liability ? '-' : ''}${fmt(item.value, currencySymbol)}`]), title, liability ? [2] : []);
  };
  drawItems('Assets', ordered.assets, false);
  drawItems('Liabilities', ordered.liabilities, true);
  footer(doc);
  if (!skipDownload) doc.save(`net-worth-report-${new Date().toISOString().slice(0, 10)}.pdf`);
  return doc.output('datauristring');
}
