export function escapeReportHtml(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

/** Shared paper-report shell used for HTML downloads and browser Print PDF. */
export function createReportHtml(title: string, metadata: string, content: string): string {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>${escapeReportHtml(title)}</title><style>
    :root { --report-ink: #111827; --report-body: #374151; --report-muted: #6b7280; --report-rule: #d1d5db; --report-fill: #f7f8fa; }
    @page { size: A4; margin: 18mm; } * { box-sizing: border-box; }
    body { margin: 0; background: #fff; color: var(--report-body); font: 15px/1.5 -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }
    .report { max-width: 820px; margin: 0 auto; padding: 36px; } .brand, .metadata, th, .metric-label { color: var(--report-muted); }
    .brand { font-size: 11px; letter-spacing: .04em; text-transform: uppercase; } h1 { margin: 5px 0 4px; padding-bottom: 10px; border-bottom: 1px solid var(--report-rule); color: var(--report-ink); font-size: 30px; letter-spacing: -.02em; }
    .metadata { font-size: 12px; } .hero { margin: 26px 0 18px; } .metric-label { font-size: 12px; font-weight: 600; letter-spacing: .04em; text-transform: uppercase; } .metric-value { color: var(--report-ink); font-size: 32px; font-weight: 700; letter-spacing: -.025em; }
    .summary { display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; margin: 18px 0 26px; } .summary-card { padding: 14px 16px; border: 1px solid var(--report-rule); } .summary-value { color: var(--report-ink); font-size: 20px; font-weight: 700; }
    section { margin: 26px 0; break-inside: avoid; } h2 { margin: 0 0 8px; padding-bottom: 7px; border-bottom: 1px solid var(--report-ink); color: var(--report-ink); font-size: 17px; }
    table { width: 100%; border-collapse: collapse; table-layout: fixed; } th, td { padding: 9px 7px; border-bottom: 1px solid #e5e7eb; text-align: left; overflow-wrap: anywhere; } th { background: var(--report-fill); font-size: 10px; letter-spacing: .05em; text-transform: uppercase; } td { font-size: 12px; } .num { text-align: right; font-variant-numeric: tabular-nums; } .negative { color: #b91c1c; } .empty { color: #9ca3af; text-align: center; } .footer { margin-top: 34px; padding-top: 12px; border-top: 1px solid var(--report-rule); color: #9ca3af; font-size: 10px; }
    @media print { .report { max-width: none; padding: 0; } }
  </style></head><body><main class="report"><div class="brand">TakeHomeCalc</div><h1>${escapeReportHtml(title)}</h1><div class="metadata">${escapeReportHtml(metadata)}</div>${content}<div class="footer">Generated by TakeHomeCalc · Not financial advice</div></main></body></html>`;
}
